# AUDUSD Currency Configuration
# Optimized for AUD/USD major currency pair analysis

currency_pair: "AUDUSD"
description: "Optimized configuration for AUD/USD major currency pair with high liquidity"

classification:
  # Price precision settings
  micro_pip_size: 0.00001
  true_pip_size: 0.0001
  
  # Time window settings
  ticks_per_bin: 100
  lookforward_offset: 500
  lookforward_input: 5000
  lookback_rows: 5000
  
  # Classification bins
  nbins: 13
  
  # Bin thresholds optimized for AUDUSD volatility patterns
  bin_thresholds:
    13:
      100:
        5000:
          bin_1: 0.47
          bin_2: 1.55
          bin_3: 2.69
          bin_4: 3.92
          bin_5: 5.45
          bin_6: 7.73
        3000:
          bin_1: 0.5
          bin_2: 1.7
          bin_3: 3.0
          bin_4: 4.3
          bin_5: 6.0
          bin_6: 8.45
          
sampling:
  sampling_mode: "consecutive"
  coverage_percentage: 0.8
  end_tick_strategy: "uniform_random"
  min_tick_spacing: 100
  seed: 42
  max_samples: null

# Processing parameters
features:
  - "volume"

# Performance settings
batch_processing:
  chunk_size: 100000
  parallel_workers: 4
  memory_limit_gb: 8