# EURJPY Currency Configuration
# Optimized for EUR/JPY cross-currency pair with JPY pip size

currency_pair: "EURJPY"
description: "Optimized configuration for EUR/JPY cross with JPY pip size adjustments"

classification:
  # Price precision settings - JPY pairs use different pip sizes
  micro_pip_size: 0.001
  true_pip_size: 0.01
  
  # Time window settings
  ticks_per_bin: 100
  lookforward_offset: 500
  lookforward_input: 4000
  lookback_rows: 4000
  
  # Classification bins
  nbins: 13
  
  # Bin thresholds adjusted for JPY cross volatility
  bin_thresholds:
    13:
      100:
        4000:
          bin_1: 4.7   # Adjusted for JPY pip size (multiply by 100)
          bin_2: 15.5
          bin_3: 26.9
          bin_4: 39.2
          bin_5: 54.5
          bin_6: 77.3
        5000:
          bin_1: 4.2
          bin_2: 14.8
          bin_3: 25.1
          bin_4: 37.6
          bin_5: 52.3
          bin_6: 74.8

sampling:
  sampling_mode: "consecutive"
  coverage_percentage: 0.75
  end_tick_strategy: "uniform_random"
  min_tick_spacing: 120
  seed: 42
  max_samples: null

# Processing parameters
features:
  - "volume"

# Performance settings
batch_processing:
  chunk_size: 90000
  parallel_workers: 4
  memory_limit_gb: 8