# GBPUSD Currency Configuration
# Optimized for GBP/USD with higher volatility adjustments

currency_pair: "GBPUSD"
description: "Optimized configuration for GBP/USD with volatility adjustments for Brexit-era trading"

classification:
  # Price precision settings
  micro_pip_size: 0.00001
  true_pip_size: 0.0001
  
  # Time window settings - shorter windows for higher volatility
  ticks_per_bin: 100
  lookforward_offset: 500
  lookforward_input: 3000  # Shorter window for volatile pair
  lookback_rows: 3000
  
  # Classification bins
  nbins: 13
  
  # Bin thresholds adjusted for GBPUSD higher volatility
  bin_thresholds:
    13:
      100:
        3000:
          bin_1: 0.6
          bin_2: 1.8
          bin_3: 3.2
          bin_4: 4.8
          bin_5: 6.7
          bin_6: 9.1
        5000:
          bin_1: 0.52
          bin_2: 1.65
          bin_3: 2.95
          bin_4: 4.45
          bin_5: 6.25
          bin_6: 8.85

sampling:
  sampling_mode: "consecutive"
  coverage_percentage: 0.7  # Lower coverage for volatile pair
  end_tick_strategy: "uniform_random"
  min_tick_spacing: 150
  seed: 42
  max_samples: null

# Processing parameters
features:
  - "volume"

# Performance settings
batch_processing:
  chunk_size: 80000
  parallel_workers: 4
  memory_limit_gb: 8